const products = [
  {
    id: 1,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ1',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 2,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ2',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-novels',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 3,
    type: 'myanmar-books',
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ3',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 4,
    type: 'myanmar-books',
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ4',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-technologies',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 5,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ5',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-religious',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 6,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ6',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 7,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ7',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 8,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ8',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 9,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 10,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-novels',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 11,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 12,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 13,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-technologies',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 14,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 15,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-technologies',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 16,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 17,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-technologies',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 18,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-religious',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 19,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138624/bookIDOL/Ebook_obb8pk.jpg',
    type: 'english-books',
    title: 'Real Life',
    author: 'Brandon Taylor',
    bookType: 'english-technologies',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 20,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ9',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-stories',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
  {
    id: 21,
    img:
      'https://res.cloudinary.com/devidol/image/upload/v1663138625/bookIDOL/MBook_ykoflc.jpg',
    type: 'myanmar-books',
    title: 'ဂရုမစိုက်ခြင်း အနုပညာ10',
    author: 'ဆရာချမ်းမြေ့ဝင်း ဘာသာပြန်သည်',
    bookType: 'myanmar-technologies',
    cartQuantity: 0,
    page: 332,
    price: 2000,
  },
]

export default products;